# Generated by Django 4.1.4 on 2022-12-25 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.TextField()),
                ("PhoneNum", models.TextField()),
                ("Email", models.EmailField(max_length=254)),
                ("JobPos", models.TextField()),
                ("IdentityNum", models.TextField()),
                (
                    "BelongCom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Company.department",
                    ),
                ),
                (
                    "RootCom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Company.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "UID",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("PassWd", models.CharField(max_length=10, unique=True)),
                ("Authorization", models.IntegerField(blank=True, null=True)),
                (
                    "DetailInfo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Human.employee"
                    ),
                ),
            ],
        ),
    ]
