# Generated by Django 4.1.4 on 2022-12-23 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ComName", models.TextField()),
                ("Scope1", models.IntegerField()),
                ("Scope2", models.IntegerField()),
                ("Scope3", models.IntegerField()),
                ("Depth", models.IntegerField()),
                ("Classification", models.TextField(blank=True, null=True)),
                ("Description", models.TextField(blank=True, null=True)),
                ("Location", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "BelongCom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="BelongCom",
                        to="Carbon.company",
                    ),
                ),
                (
                    "RootCom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="RootCom",
                        to="Carbon.company",
                    ),
                ),
                (
                    "SelfCom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="SelfCom",
                        to="Carbon.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.TextField()),
                ("PhoneNum", models.TextField()),
                ("Email", models.EmailField(max_length=254)),
                ("JobPos", models.TextField()),
                ("IdentityNum", models.TextField()),
                (
                    "BelongCom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Carbon.department",
                    ),
                ),
                (
                    "RootCom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Carbon.company"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "UID",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("PassWd", models.CharField(max_length=10, unique=True)),
                ("Authorization", models.IntegerField(blank=True, null=True)),
                (
                    "DetailInfo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Carbon.employee",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="Admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="AdminCom",
                to="Carbon.employee",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="Chief",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ChiefCom",
                to="Carbon.employee",
            ),
        ),
        migrations.CreateModel(
            name="CarbonInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("StartDate", models.DateField()),
                ("EndDate", models.DateField()),
                ("Location", models.TextField()),
                ("Scope", models.IntegerField()),
                ("Category", models.IntegerField()),
                ("Division", models.TextField()),
                (
                    "Chief",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ChiefCarbonInfo",
                        to="Carbon.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Carbon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CarbonActivity", models.TextField()),
                ("CarbonData", models.FloatField()),
                ("CarbonUnit", models.TextField()),
                ("CarbonTrans", models.FloatField()),
                (
                    "BelongCom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="BelongComCarbon",
                        to="Carbon.company",
                    ),
                ),
                (
                    "CarbonInfo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Carbon.carboninfo",
                    ),
                ),
                (
                    "RootCom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="RootComCarbon",
                        to="Carbon.company",
                    ),
                ),
            ],
        ),
    ]
