# Generated by Django 4.1.4 on 2022-12-25 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Human", "0001_initial"),
        ("Carbon", "0001_initial"),
        ("Company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carboninfo",
            name="Chief",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ChiefCarbonInfo",
                to="Human.employee",
            ),
        ),
        migrations.AddField(
            model_name="carbon",
            name="BelongCom",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="BelongComCarbon",
                to="Company.company",
            ),
        ),
        migrations.AddField(
            model_name="carbon",
            name="CarbonInfo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Carbon.carboninfo",
            ),
        ),
        migrations.AddField(
            model_name="carbon",
            name="RootCom",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="RootComCarbon",
                to="Company.company",
            ),
        ),
    ]
