# Generated by Django 4.1.3 on 2022-12-04 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Carbon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="Description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin",
                to="Carbon.user_employee",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="chief",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chief",
                to="Carbon.user_employee",
            ),
        ),
    ]
