# Generated by Django 4.1.3 on 2022-11-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carbon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_employee',
            name='Authorization',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_employee',
            name='IdentityNum',
            field=models.TextField(),
        ),
    ]
