# Generated by Django 4.1.3 on 2022-11-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carbon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbon',
            name='Category',
            field=models.IntegerField(null=True),
        ),
    ]
