# Generated by Django 4.1.3 on 2022-12-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Carbon", "0002_department_description_department_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="Classification",
            field=models.TextField(blank=True, null=True),
        ),
    ]
