# Generated by Django 4.1.3 on 2022-11-13 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carbon', '0002_alter_user_employee_authorization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='upper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Carbon.department'),
        ),
    ]
