# Generated by Django 4.1.4 on 2022-12-25 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Carbon", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carbon",
            name="CarbonInfo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Carbon.carboninfo",
            ),
        ),
    ]
