# Generated by Django 4.1.3 on 2022-12-04 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Carbon", "0003_department_classification"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="Classification",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="Description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adminCom",
                to="Carbon.user_employee",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="chief",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chiefCom",
                to="Carbon.user_employee",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adminDepart",
                to="Carbon.user_employee",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="chief",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chiefDepart",
                to="Carbon.user_employee",
            ),
        ),
    ]
