# Generated by Django 4.1.3 on 2022-12-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Carbon", "0004_company_classification_company_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carbon",
            name="Division",
            field=models.TextField(null=True),
        ),
    ]
