# Generated by Django 4.1.4 on 2022-12-25 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ComName", models.TextField()),
                ("Scope1", models.IntegerField()),
                ("Scope2", models.IntegerField()),
                ("Scope3", models.IntegerField()),
                ("Classification", models.TextField(blank=True, null=True)),
                ("Description", models.TextField(blank=True, null=True)),
                ("Location", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Depth", models.IntegerField()),
                (
                    "BelongCom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="BelongCom",
                        to="Company.company",
                    ),
                ),
                (
                    "RootCom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="RootCom",
                        to="Company.company",
                    ),
                ),
                (
                    "SelfCom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="SelfCom",
                        to="Company.company",
                    ),
                ),
            ],
        ),
    ]
