# Generated by Django 4.1.4 on 2022-12-25 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Human", "0001_initial"),
        ("Company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="Admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="AdminCom",
                to="Human.employee",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="Chief",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ChiefCom",
                to="Human.employee",
            ),
        ),
    ]
