# Generated by Django 4.1.4 on 2022-12-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Company", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="DepartmentName",
            field=models.TextField(default=None),
        ),
    ]
